#
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
#

Name:       harbour-parkingchaos

# >> macros
# << macros

Summary:    Rush hour in your parking lot
Version:    1.0
Release:    1
Group:      Qt/Qt
License:    GPLv3+
URL:        https://github.com/ichthyosaurus/harbour-parkingchaos
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-parkingchaos.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  desktop-file-utils

%description
Parking Chaos is a clone of the famous "Rush Hour" or "Traffic Jam" game,
written from scratch based on ParkMeeCrazy.
Move your vehicle to the exit on the right by dragging others out of the way.
Horizontal cars can only move left and right, vertical ones can only move
up and down.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
printf "#ifndef APP_VERSION\n#define APP_VERSION \"%s\"\n#endif" "%{version}" > version.h
# << build pre

%qmake5

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
